# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "wordpress_env_path", "new": "<Removed>" }
    - { "old": "wordpress_config_path", "new": "<Removed>" }
    - { "old": "wordpress_uploads_config_location", "new": "<Removed>" }
    - { "old": "wordpress_environment_variables_extension", "new": "wordpress_environment_variables_additional_variables" }

- name: Fail if required WordPress settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - wordpress_uid
    - wordpress_gid
    - wordpress_hostname
    - wordpress_container_network

- name: Run if Traefik is enabled
  when: wordpress_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Wordpress are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - wordpress_container_labels_traefik_hostname
        - wordpress_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `wordpress_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if wordpress_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          wordpress_container_labels_traefik_path_prefix (`{{ wordpress_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/wordpress`).
      when: "wordpress_container_labels_traefik_path_prefix != '/' and wordpress_container_labels_traefik_path_prefix[-1] == '/'"
